version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: useradm-postgres
    environment:
      POSTGRES_DB: useradm
      POSTGRES_USER: useradm
      POSTGRES_PASSWORD: useradm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
